### ISSUE TITLE
Replace SMS with Email

### ISSUE THREAD

**Issue by bobozar** [jazzband/django-two-factor-auth#277]
Hello, is it possible to use email option instead of sms for the gateway. Instead of sending sms to phones, can I set it to send the codes to emails?

**Comment by moggers87** [comment]
I think this is already covered by https://github.com/Bouke/django-two-factor-auth/pull/267

**Comment by bobozar** [comment]
Okay.. checked it out.. but no proper documentation on using email for 2FA. I guess there should be a variable in the settings one can change. E.g 2FA_BACKEND ='sms' or 2FA_BACKEND ='email'.

I hope you get my point?

**Comment by moggers87** [comment]
That PR has also added documentation for enabling Email based 2FA.

**Comment by moggers87** [comment]
I should mention that the PR in question still needs some work on it, so for now it's probably best to do without.

**Comment by claudep** [comment]
See #404.
