### ISSUE TITLE
Add email verification option

### ISSUE THREAD

**Issue by Fatiima-Ezzahra** [jazzband/django-two-factor-auth#404]
## Expected Behavior
This will add an option to send an email with the token to further verify the user.

## Current Behavior
There are many options for two factor authentication, but sending emails is not one of them.

## Possible Solution
Adding an EmailDevice and changing the views and templates to incorporate this option.

## Context
I used django-two-factor-auth to enable 2FA in a project, but I needed to send an email instead of the other options.

**Comment by claudep** [comment]
Current PR addressing this issue is #478.

**Comment by claudep** [comment]
Fixed in b864c8206.
