### ISSUE TITLE
Rewriting existing login classes or use signals to run post login actions

### ISSUE THREAD

**Issue by LeoWelter** [jazzband/django-two-factor-auth#406]
I’m implementing tfa in my site. My current login view does a lot of actions like checking for tasks since last login after a successful login. Should I use signals to run these actions or extend the login view of dtfa?

**Comment by moggers87** [comment]
You can either use the `user_logged_in` signal from `django.contrib.auth` or override the `done` method in `two_factor.views.core.LoginView`.

**Comment by claudep** [comment]
Closing as an answer was given.
