### ISSUE TITLE
Running migrations shows missing expected migrations due to DEFAULT_AUTO_FIELD changes in Django

### ISSUE THREAD

**Issue by vaughnkoch** [jazzband/django-two-factor-auth#436]
This looks like the same issue as https://github.com/django-otp/django-otp/issues/93. 

## Current Behavior

```
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, otp_static, otp_totp, sessions, two_factor, users
Running migrations:
  No migrations to apply.
  Your models in app(s): 'otp_static', 'otp_totp', 'two_factor' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

## Expected Behavior
Running migrate should not show an error.

## Possible Solution

The simplest solution seems to be to specify an explicit primary key for this model.  A workaround is to set DEFAULT_AUTO_FIELD in settings.py so Django doesn't complain.

`DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'`

See more info at https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys.

## Steps to Reproduce

- Install Django 3.2.8
- Install django-two-factor-auth  1.13.1
- `python manage.py migrate`

## Your Environment
Django 3.2.8
django-two-factor-auth  1.13.1
django-otp 1.1.1

**Comment by moggers87** [comment]
Specifying an explicit PK would be the best way to go IMO.

**Comment by peymanslh** [comment]
I think we could close this issue, as far as Django adds `DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'` as a default in new projects `settings.py` and a new installation of `django-two-factor-auth` doesn't have this problem anymore.

**Comment by claudep** [comment]
I don't think we can depend on projects setting `AutoField` as default. I'd suggest to follow django-otp approach in https://github.com/django-otp/django-otp/commit/7ef5b25c8a715 (setting `default_auto_field` in default app config).

**Comment by peymanslh** [comment]
Sure, I work on this issue and update my PR based on your suggestion.
