### ISSUE TITLE
FIDO support

### ISSUE THREAD

**Issue by Be-ing** [jazzband/django-two-factor-auth#437]
FIDO is more secure (no shared secret, resistant to phishing) and easier to use (just push a button) than OTP. It would be great if this library supported it.

**Comment by moggers87** [comment]
How does FIDO work then?

**Comment by Be-ing** [comment]
https://fidoalliance.org/fido2/
https://webauthn.io/

**Comment by jpaniagualaconich** [comment]
#408 does WebAuthn.

**Comment by moggers87** [comment]
@jpaniagualaconich will that PR be enough to say we support FIDO?

**Comment by jpaniagualaconich** [comment]
@moggers87 Yes.

**Comment by Frikster** [comment]
#408 is merged so this issue can be closed (huzzah!)
