### ISSUE TITLE
Remove upper limit to qrcode dependency

### ISSUE THREAD

**Issue by claudep** [jazzband/django-two-factor-auth#438]
Currently, django-two-auth-factor has an upper limit to the qrcode version. In a project where I use qrcode-7.3.1, this causes a downgrade of the dependency in the project (or a conflict if my project setup a hard dep on qrcode > 7).
Could that upper limit be dropped, please?

**Comment by Bouke** [comment]
The reason for having an upper limit is to prevent breakage if a backwards-incompatible version were to be released. A major version bump often indicates such backwards-incompatible changes when adhering semver. So I'd suggest upping the limit if there's no breakage.
