### ISSUE TITLE
Support django 4.0

### ISSUE THREAD

**Issue by matthewhegarty** [jazzband/django-two-factor-auth#440]
## Expected Behavior

[Django 4.0](https://docs.djangoproject.com/en/4.0/releases/4.0/) is now the latest official release.

However, testing my app with django 4.0 gives the following error (via `python -Wa manage.py test`):

```
  File "/home/matthew/.virtualenvs/dev/lib/python3.9/site-packages/two_factor/admin.py", line 7, in <module>
    from django.utils.http import is_safe_url
ImportError: cannot import name 'is_safe_url' from 'django.utils.http'
```

This is due to [this deprecation](https://django.readthedocs.io/en/stable/internals/deprecation.html#deprecation-removed-in-4-0).

## Possible Solution

[more info](https://django.readthedocs.io/en/stable/releases/3.0.html#deprecated-features-3-0)

> To avoid possible confusion as to effective scope, the private internal utility is_safe_url() is renamed to url_has_allowed_host_and_scheme(). That a URL has an allowed host and scheme doesn’t in general imply that it’s “safe”. It may still be quoted incorrectly, for example. Ensure to also use iri_to_uri() on the path component of untrusted URLs.

## Your Environment

* Python version: 3.9
* Django version: 4.0
* django-otp version: 1.1.1
* django-two-factor-auth version: 1.13.1

**Comment by matthewhegarty** [comment]
Additionally:

```
/home/matthew/.virtualenvs/dev/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'two_factor' defines default_app_config = 'two_factor.apps.TwoFactorConfig'. Django now detects this configuration automatically. You can remove default_app_config.

```

**Comment by claudep** [comment]
Commit 0439c21262c6 should have fixed this, but no new release was made since that change.

**Comment by larsrinn** [comment]
Is there an ETA for this release?

**Comment by claudep** [comment]
Is there an issue with the maintainership of this package? Should be time to move to Jazzband?

**Comment by 9mido** [comment]
+1 for Jazzband. If everybody is on board, we need to create an issue in the jazzband help link and then we need to follow the jazzband transfer guidelines. 

https://github.com/jazzband/help

https://jazzband.co/

https://jazzband.co/about/guidelines

https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by claudep** [comment]
@Bouke, @moggers87, we understand you are volunteers and that you also deserve holidays and rest. However this missing release frustrates many. Could you please take one minute to take position regarding a move to Jazzband, and in the case you are against that, what are your future plans to improve the current situation?

**Comment by Bouke** [comment]
There's already the [intent to move the project over to jazzband](https://github.com/jazzband/help/issues/180). I could use your help in getting things ready, there's a [checklist here](https://github.com/jazzband/django-two-factor-auth/issues/444). Thank you all for quite a ride.

**Comment by claudep** [comment]
Awesome, thanks a lot. I'll see if I can spend some time on some tasks tomorrow :fireworks:

**Comment by karanaggarwal1** [comment]
@Bouke sorry to bother you during the holidays but as we wait for the checklist items to be completed, do you have any thoughts on improving the current situation with a release?

**Comment by karanaggarwal1** [comment]
Thanks a lot for merging the changes, when would the next release be? The [PyPI page](https://pypi.org/project/django-two-factor-auth/#history) still has version 1.13.1, is that expected?

**Comment by claudep** [comment]
There are still some administrative stuff to solve before being able to release through the Jazzband system, but I firmly hope a release can happen within the next two weeks.
