### ISSUE TITLE
Server Error (500) on example-two-factor-auth.herokuapp.com login page

### ISSUE THREAD

**Issue by MarcMichalsky** [jazzband/django-two-factor-auth#442]
The [login page](https://example-two-factor-auth.herokuapp.com/account/login/) displays a server error.

**Comment by anuragkulkarni** [comment]
Same issue was experienced by me showing me server error 500

**Comment by statsconchris** [comment]
Yes. the example app is not working. Any comments on that?

**Comment by moggers87** [comment]
We're aware, but no one has the bandwidth to fix it right now.

**Comment by statsconchris** [comment]
Thanks. Is this the reason why the option to choose from the list: i) token, ii) sms, iii) call,  iv) jubikey is not there. When I click start 2FA in the setup page, it automatically jumps to the token option only and I don't have access to the other options...Is there a way to solve this? Thanks
