### ISSUE TITLE
Bug in loop over tolerance in TOTPDeviceForm?

### ISSUE THREAD

**Issue by mbakereth** [jazzband/django-two-factor-auth#455]
In the clean_token function of TOTPDeviceForm in two_factor/forms.py. there is the following line (163):

    for offset in range(-self.tolerance, self.tolerance):

self.tolerance is hardcoded to 1, which means this loop will range over the values -1, 0.  Did you intend it to range over -1, 0, 1?  If this is the case, the line should be

    for offset in range(-self.tolerance, self.tolerance+1):

I find that, without this, I cannot complete the 2FA activation when using Google Authenticator to scan the QR code.

There is a similar line in two_factor/models.py (90):

        for drift in range(-5, 1):

This will range over the values (-5, -4, -3, -2, -1, 0).  Personally, this does not create an issue for me but the one in clean_token does.

If you don't want to change this, is it possible to make tolerance a settable parameter?  I can see now way of changing it in my code without a monkey patch.

**Comment by claudep** [comment]
Would you like to suggest a patch with a regression test?

**Comment by mbakereth** [comment]
Thanks.  I've made a change in my fork - shall I do a pull request?

Changing 
  for offset in range(-self.tolerance, self.tolerance):
to 
  for offset in range(-self.tolerance, self.tolerance+1):

Added a new unit test for the form that tests TOTPs with offset of -1, 0 and +1 are valid and -2, +2 are not.  All existing tests pass.

**Comment by claudep** [comment]
> shall I do a pull request?

Yes, please!
