### ISSUE TITLE
DisableView success_url

### ISSUE THREAD

**Issue by last-partizan** [jazzband/django-two-factor-auth#460]
https://github.com/jazzband/django-two-factor-auth/blob/dcf23680a788c588bb0a1496e22badefd7dca0db/two_factor/views/profile.py#L56

https://github.com/jazzband/django-two-factor-auth/commit/e1812e14a2dda8a6e4fc9d4d1c5651890c5d5164

@moggers87 What's logic behind passing `success_url` from DisableView as `login_url` to `otp_required` decorator?

If i understand it right:
- `success_url` - URL to which we want to redirect user after successfuly disabling two factor auth.
- `login_url` in `@otp_required` - URL to which redirect user, if user not authenticated using 2fa.

It should be two different URLs, am i right?

I see your comment:

```python
    def dispatch(self, *args, **kwargs):
        # We call otp_required here because we want to use self.success_url as
        # the login_url. Using it as a class decorator would make it difficult
        # for users who wish to override this property
        fn = otp_required(super().dispatch, login_url=self.success_url, redirect_field_name=None)
        return fn(*args, **kwargs)
```

Users actually want to override success_url, but not `login_url`. `login_url` should always be the same. Or am i missing something?

**Comment by moggers87** [comment]
> It should be two different URLs, am i right?

In this case it is assumed that the user is already logged in and the default for `success_url` is `settings.LOGIN_REDIRECT_URL`, which is where users get sent to once they've logged in successfully. In the example app this resolves to `twofactor:profile`. So: if the user succeeds in disabling 2FA then we want them to go back to their profile and if they already have it disabled then we also want them to go back to their profile.

The only case where things would get a little weird is if the user is not logged in at all: the user would be redirected to their profile, which would /then/ redirect to the login page.

I hope that clears up why we're using `login_url` in this fashion.

**Comment by last-partizan** [comment]
I think i understand it now, thanks.
