### ISSUE TITLE
Duplicate query for LoginView

### ISSUE THREAD

**Issue by pickfire** [jazzband/django-two-factor-auth#465]
## Expected Behavior

`LoginView` should not have extra duplicated and unnecessary queries.

## Current Behavior

Each step in `LoginView` seemed to be calling `has_token_step` and `has_backup_view`, and both calls `default_device` for the same thing but the results are not cached which results in duplicated queries.

## Possible Solution

Cache `has_token_step` and `has_backup_view` or maybe have cached version of `default_device`. At least we get this in django debug toolbar.

![image](https://user-images.githubusercontent.com/4687791/151141582-9ef2a995-8d87-462e-a63f-59d405db33c3.png)

## Steps to Reproduce (for bugs)

1. Use `LoginView`, I can't really test examples in two-factor-auth out so not sure how to test out a smaller version, so not sure if it's just us or if it's intended.

## Context

Reduce the login loading time, but still the improvements probably not that significant, at least from my side I can see ~32ms improvements probably if there is a fix.

## Your Environment

* Browser and version: firefox 96
* Python version: 3.8
* Django version: 3.1
* django-otp version: 1.1.3
* django-two-factor-auth version: 1.13.1
* Link to your project: closed source

**Comment by moggers87** [comment]
Good find! Even users without 2FA are affected by this.

**Comment by moggers87** [comment]
Interesting, rolling back to django-two-factor-auth 1.11 reduces the number queries from 40 to 20. Still bad, but clearly something recent has made it worse.

**Comment by ben-qr** [comment]
This issue is still present for users that have no 2fa devices setup (because the is no default to be cached). Can this issue be reopened?
I suggest something like -
```
def default_device(user):
    if not user or user.is_anonymous:
        return
    if hasattr(user, USER_DEFAULT_DEVICE_ATTR_NAME):
        return getattr(user, USER_DEFAULT_DEVICE_ATTR_NAME)

    _default_device = None
    for device in devices_for_user(user):
        if device.name == 'default':
            _default_device = device
            break

    setattr(user, USER_DEFAULT_DEVICE_ATTR_NAME, _default_device)
    return _default_device
```
