### ISSUE TITLE
When Yubikey token is written down, the page keeps loading until timeout (token is not verified)

### ISSUE THREAD

**Issue by statsconchris** [jazzband/django-two-factor-auth#486]
## Expected Behavior
This happens when I set the 2FA. I should get something like: "congratulations your yubikey is set" but the page keeps loading forever until timeout

## Current Behavior
Immediately after filling the token by pressing my yubikey, page loads but doesn't move to the next step

## Possible Solution
It worked in my localhost, but failed in a real server with SSL

Anybody has the same issue? Thanks

**Comment by moggers87** [comment]
Could you provide the following:

* Browser and version
* Python version
* Django version
* django-otp version
* django-two-factor-auth version

**Comment by statsconchris** [comment]
Browser and version: Chrome, Firefox, different versions (e.g., chrome v 990.4844.74, firefox v91)
Python version: 3.9.2
Django version : 4.0.3
django-otp version: 1.1.3
django-two-factor-auth version : 1.13.2

Im using the default service, 
and my remoteyoubikey_device table stores the hex code but multiple times for the same user (likely because I try several times and the page loads without moving to the next step)

id | name | confirmed | public_id | service_id | user_id
1   default       1             ccc5262        1               1
2   default       1             ccc5262        1               1
3   default       1             ccc5262        1               1
4   default       1             ccc5262        1               1

It should appear only once,

**Comment by statsconchris** [comment]
The log file shows:
[wsgi:error] [pid xxxx:tid xxxxxxxxxxxxxx] [client xxx.xxx.xxx.x:xxxx] Timeout when reading response headers from daemon process....
Any help?

**Comment by statsconchris** [comment]
Also checking the Inno DB Status I get in transactions:

7 lock struct(s), heap size 1136, 2 row lock(s)

and the processlist of the yubikey falls asleep

**Comment by statsconchris** [comment]
Dear all, you can close this.
It has been resolved with the latest update. Not sure what was the cause but it is fixed.
regards
