### ISSUE TITLE
Release 1.14.0

### ISSUE THREAD

**Issue by claudep** [jazzband/django-two-factor-auth#501]
I'd like to make a 1.14.0 release soon. @moggers87, ok for that? I'll prepare a commit with Changelog and such in the coming days.

**Comment by claudep** [comment]
I just pushed the updated translatable strings to Transifex.

**Comment by claudep** [comment]
#507 is the PR for the Changelog, but #505 and #506 should be merged first, then the translations should be pulled from Transifex.

**Comment by moggers87** [comment]
Pulled the latest translations from Transifex. PR here: https://github.com/jazzband/django-two-factor-auth/pull/508

Once that's been merged we can tag and upload a release

**Comment by claudep** [comment]
Crap, I tagged and pushed 1.14.0, then realized that we missed bumping version in some places. So I reverted the tag and prepared #509.

**Comment by moggers87** [comment]
Tagged a new release and I think we just wait for CI to do the upload now, right?

**Comment by moggers87** [comment]
Done and done: https://pypi.org/project/django-two-factor-auth/1.14.0/

Thanks @claudep for taking the lead on getting a release out :smiley_cat:

**Comment by claudep** [comment]
:champagne:
