### ISSUE TITLE
Add white background to QR image for browsers in dark mode

### ISSUE THREAD

**Issue by jcu721** [jazzband/django-two-factor-auth#503]
My computer preference theme is set to Dark. Django interprets this nicely, but the QR code shows up as dark on dark and is very difficult to see. Can be read by some QR readers but not by others. 

## Expected Behavior
The QR image should always have a white background instead of transparent. 
Browsers with dark mode enabled that are overriding the base template should be able to have a readable QR image that can be scanned easily. 

## Current Behavior
When dark mode is enabled, the background is set to black and the transparent image shows up directly on the default black background. It can be read by one phone I tested with, but not the 1Password browser QR scanner. It is also very difficult to even visually tell there is a QR code there.  
<img width="750" alt="Screen Shot 2022-05-16 at 6 26 25 PM" src="https://user-images.githubusercontent.com/2374425/168692457-a92cd9cc-4531-47ca-a335-069fbd58c21d.png">

## Possible Solution
Hardcode the style background to be white on the img tag. 
`<p><img src="{{ QR_URL }}" alt="QR Code" style="background:white"/></p>`

This results in an easy to see QR image with a nice margin/border:
<img width="175" alt="Screen Shot 2022-05-16 at 6 28 16 PM" src="https://user-images.githubusercontent.com/2374425/168693315-51dcfc67-7078-46b0-a732-1173b5bbc66a.png">

## Steps to Reproduce (for bugs)
1. Have a custom _base.html template that extends the base django template: `{% extends "admin/base.html" %}`
2. Have computer (mac, in my case) theme set to dark (System Preferences -> General -> Appearance)
3. Navigate through 2FA setup to get to QR page
4. Try to scan with in browser QR scanner

## Context
The dark on dark QR code can actually be read by a phone (tested with iphone 13 mini), but cannot be read by the 1Password in-browser QR scanner. I'd imagine it would also work poorly with older phones / certain cameras. 

## Your Environment
* Browser and version: Firefox 100.0
* Python version: 3.7.7
* Django version: 3.2.13
* django-otp version: 1.1.3
* django-two-factor-auth version: 1.13.2

**Comment by claudep** [comment]
@jcu721, do you plan to work on a patch?

**Comment by jcu721** [comment]
@claudep  just opened a PR, https://github.com/jazzband/django-two-factor-auth/pull/504, let me know if I need to do any further testing.
