### ISSUE TITLE
You are linking to a troll website

### ISSUE THREAD

**Issue by kennylajara** [jazzband/django-two-factor-auth#542]
## Expected Behavior
Link to PyPi or Read the doc (I prefer this)

## Current Behavior
You at linking to `http://example-two-factor-auth.herokuapp.com/` and this URL makes fun of you

## Possible Solution
Change the link to your documentation

## Steps to Reproduce (for bugs)

1. Go to https://github.com/jazzband/django-two-factor-auth
2. Click on the link below the **About** section on the top right.
3. ...
4. Profit

## Context
¯\\_(ツ)_/¯

## Your Environment

* Browser and version:
* Python version:
* Django version:
* django-otp version:
* django-two-factor-auth version:
* Link to your project:

**Comment by claudep** [comment]
@moggers87, @jezdez, has anyone of you access to the About section edition?

**Comment by jezdez** [comment]
Fixed!

**Comment by claudep** [comment]
:heart_eyes:
