### ISSUE TITLE
Login page usability - HTML5 validation prevents clicking on "Use Backup Token"

### ISSUE THREAD

**Issue by PetrDlouhy** [jazzband/django-two-factor-auth#545]
There are few problems with default login page usability.

## Expected Behavior

Only the "Next" button triggers form validation.

## Current Behavior
Both "Use Backup Token" or "Back" buttons can't be clicked when user enters invalid code, because of HTML5 field validation:
![Snímek obrazovky_2022-09-26_12-20-21](https://user-images.githubusercontent.com/156755/192257441-29e1bfeb-5f88-48d8-86b2-d8d08d45992a.png)

## Possible Solution

I have solved this in my project by creating second form containing only the "Use Backup Token" and placing it on bottom of the page (which I consider better, because it doesn't disrupt the Enter 2FA form):
```htmldjango
    {% if backup_tokens %}
       <hr/>
       <small>
       <form method="post" action="" class="bkit-registration__form">
           {% csrf_token %}
            <p>{% trans "As a last resort, you can use a backup token:" %}</p>
            <p>
                <button name="wizard_goto_step" type="submit" value="backup"
                    class="btn btn-sm btn-secondary btn-block">{% trans "Use Backup Token" %}</button>
            </p>
       </form>
       </small>
    {% endif %}

```

But this doesn't solve the problem with the "Back" button.

## Steps to Reproduce (for bugs)

1. Configure 2FA with security codes.
2. Log in
3. Enter code "xyzabc"
4. Pres "Use Backup Token" or "Back"

## Context
This might be problem especially if user did enter the backup code into the 2FA code field - if he expects that the code could be entered in this field, he will get very confused possibly unable to change his mind model to be able to delete the code and click on the button again.

## Your Environment

* Browser and version: Chrome Verze 102.0.5005.115
* Python version: 3.10.4
* Django version: 4.0.7
* django-otp version: 1.1.3
* django-two-factor-auth version: 1.14.0
* Link to your project: www.blenderkit.com

**Comment by claudep** [comment]
One problem at a time :-)
