### ISSUE TITLE
test_webauthn_attestation_and_assertion flaky?

### ISSUE THREAD

**Issue by claudep** [jazzband/django-two-factor-auth#548]
It looks like `two_factor.plugins.webauthn.tests.test_e2e.E2ETests.test_webauthn_attestation_and_assertion` is randomly failing with a Timeout error. @jpaniagualaconich, do you think we should augment the timeout?

**Comment by jpaniagualaconich** [comment]
@claudep 2 separate PRs:
- #553 to use a newer selenium that properly closes sockets
- #554 the timeout increase

seem to fix this issue.

**Comment by claudep** [comment]
It looks like all recent test runs were successful. Let's hope it's for good!
