### ISSUE TITLE
[Question] How to customize the text in template?

### ISSUE THREAD

**Issue by mzfr** [jazzband/django-two-factor-auth#557]
I did understand that I was supposed to add `two_factor/_base.html` to remove the banner but I want to further customize the form itself.

In `two_factor/_base.html` I have

```html
{% extends "../registration/login.html" %}
```

In the `registration/login.html` I have

```html
{% include 'header.html' %}

<div class="container">
  <div class="row">
    <div class="col-xl-5  mx-auto p-4">
      <div class="card" style="width: 25rem;">
        <div class="card-header">Login</div>
        <div class="card-body">
          <form method="post">
            {% block content %}
            {% endblock %}
          </form>
        </div>
        <div class="card-footer">
          <a href="{% url 'password_reset' %}">Reset Password</a>
        </div>
      </div>
    </div>
  </div>
</div>
```

And it looks like the following:

![image](https://user-images.githubusercontent.com/16623935/193053501-625cd993-545d-4d7e-9170-414d9576c964.png)

I've tried running the example with Django-4 but it didn't work and I'm not sure how to modify the text.

What I want is to remove the `Enter the credential` text and also want to remove the `Login` inside the `card-body`.

**Comment by bil0u** [comment]
You can override any template from [templates](https://github.com/jazzband/django-two-factor-auth/tree/master/two_factor/templates). As long as your app is imported before `two_factor` in your `INSTALLED_APPS` and the template have the exact same path relative to the `templates` directory.

Ideally you would copy all templates from the source code and make your changes from there.

See more details in [django docs](https://docs.djangoproject.com/en/4.1/howto/overriding-templates/)

**Comment by claudep** [comment]
Thanks @bil0u for answering. Closing as this is a support question, not an issue.
