### ISSUE TITLE
Example app fails with Django 4.x

### ISSUE THREAD

**Issue by bmihelac** [jazzband/django-two-factor-auth#565]
## Expected Behavior

Installing `pip install -r requirements_dev.txt` and running `make example` fails with `ImportError` stated below.
This is because `django-user-sessions` app is not compatible with Django 4.x. 

```
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/django-two-factor-auth/.venv/lib/python3.10/site-packages/django/utils/translation/__init__.py)
```
## Current Behavior

Example app does not work.

## Possible Solution

Install Django 3.2:

```bash
pip install "Django>=3.2,<4"

```

## Steps to Reproduce (for bugs)

1.Installing `pip install -r requirements_dev.txt` 
2. run `make example`
3. `ImportError` is raised

## Context
-

**Comment by claudep** [comment]
I think this is fixed now that django-user-sessions 2 was released.
