### ISSUE TITLE
back button requires me to fill field data

### ISSUE THREAD

**Issue by rubmz** [jazzband/django-two-factor-auth#572]
Setup wizard has a back button that requires form to be filled before you can step back, which isn't too rational. And seems there is a quick fix for that, which...... I am too lazy to put myself (git work...), so here it is: "formnovalidate" is a keyword that needs to be added to _wizard_actions.html like so:

```
{% if wizard.steps.prev %}
  <button name="wizard_goto_step" type="submit"
          value="{{ wizard.steps.prev }}" formnovalidate
          class="btn btn-secondary">{% trans "Back" %}</button>
{% else %}

```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser and version:
* Python version:
* Django version:
* django-otp version:
* django-two-factor-auth version:
* Link to your project:

**Comment by claudep** [comment]
Thanks for the report, but this should be fixed in master by https://github.com/jazzband/django-two-factor-auth/commit/b86a790b63bd679
