### ISSUE TITLE
хуйня повна

### ISSUE THREAD

**Issue by Ded090** [jazzband/django-two-factor-auth#574]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser and version:
* Python version:
* Django version:
* django-otp version:
* django-two-factor-auth version:
* Link to your project:

**Comment by Ded090** [comment]
криворука макака яка написала це знай то хуйня

**Comment by claudep** [comment]
Sorry, but issues must be written in English.
