### ISSUE TITLE
In django 4.1 import SuccessURLAllowedHostsMixin fails

### ISSUE THREAD

**Issue by statsconchris** [jazzband/django-two-factor-auth#575]
`site-packages/two_factor/views/core.py line 15 in <module>`
`from django.contrib.auth.views import SuccessURLAllowedHostsMixin`
`ImportError: cannot import name 'SuccessURLAllowedHostsMixin' from 'django.contrib.auth.views'`

The documentation shows
`The undocumented django.contrib.auth.views.SuccessURLAllowedHostsMixin mixin is replaced by RedirectURLMixin.`
So it needs to be updated

**Comment by claudep** [comment]
Already fixed by https://github.com/jazzband/django-two-factor-auth/commit/d00c03865a2
