### ISSUE TITLE
Webauthn templates missing on pypi for version 1.15.0

### ISSUE THREAD

**Issue by tzetter** [jazzband/django-two-factor-auth#583]
When installing version 1.15.0 of the package from pypi the two webauthn plugin JavaScript template files (https://github.com/jazzband/django-two-factor-auth/tree/1.15.0/two_factor/plugins/webauthn/templates/two_factor_webauthn) are missing.

## Expected Behavior

The `CreateCredentialJS` and `GetCredentialJS` views should use the templates for generating JavaScript used by the app.

## Current Behavior

As the files are missing from the package the views return error 500s. The super nice new Webauthn functionality does therefore not work. 

## Possible Solution

You most likely need to publish a new version of the package with the missing files included.

## Your Environment

* Python version: 3.11.1
* Django version: 4.1.5
* django-otp version: 1.1.4
* django-two-factor-auth version: 1.15.0

**Comment by claudep** [comment]
Thanks for reporting. Maybe a missing entry in MANIFEST.in?

@jpaniagualaconich, could you have a look?

**Comment by jpaniagualaconich** [comment]
oopsie, you're right @tzetter 
@claudep this should fix it (plus version bump everywhere... I updated `CHANGELOG` assuming it'll be `1.15.1`)

**Comment by hansegucker** [comment]
Hey, thanks for fixing this. Will there be an upload soon?

**Comment by claudep** [comment]
I hoped to also include updated translations. But for now, only French made progress on them.

**Comment by Natureshadow** [comment]
> I hoped to also include updated translations. But for now, only French made progress on them.

Is this supposed to mean "I will release now anyway", or "this critical fix will continue waiting for translations"?

**Comment by claudep** [comment]
If some good soul happens to approve PR #588, it will mean that a release may happen very soon after.

**Comment by Natureshadow** [comment]
Can we get this bugfix released instead of holding it back until someone verifies the French translation?

**Comment by claudep** [comment]
Nothing will happen in this package until someone steps up to help maintain it.

**Comment by Natureshadow** [comment]
> Nothing will happen in this package until someone steps up to help maintain it.

What help is needed, that does not require speaking a foreign language?

**Comment by claudep** [comment]
A general help of maintainership, that is triaging, reviewing, possibly coding at times. It requires joining the [Jazzband](https://jazzband.co/) team.
