### ISSUE TITLE
Can't override Template (two_factor/_base.html)

### ISSUE THREAD

**Issue by pwfraley** [jazzband/django-two-factor-auth#591]
I have a django 4.1 app.  In the Main Folder there is a templates folder in which I created a new folder two_factor.  I put a _base.html file in this folder.

## Expected Behavior
It should use the new _base.html template.

## Current Behavior
It still shows the _base.html template from the package.

## Possible Solution
None so far

## Steps to Reproduce (for bugs)
1. Create a new Django Project
2. Add all requirements for two_factor, and follow instruction in documentation
3. Create a Templates folder and add a folder two_factor
4. Add a file _base.html

## Context
None

## Your Environment

* Browser and version: Current Firefox
* Python version: 3.11
* Django version: 4.1
* django-otp version: 1.1.4
* django-two-factor-auth version: 1.15.0
* Link to your project: private

## Template Setup:
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'zyako.context_processors.orders_open'
            ],
        },
    },
]

**Comment by scottpashley** [comment]
@pwfraley what was your solution for this in the end (was it that you were using `base.html` instead of `_base.html` as the title updates suggest?)

**Comment by scottpashley** [comment]
> @pwfraley what was your solution for this in the end (was it that you were using `base.html` instead of `_base.html` as the title updates suggest?)

Updating this for anyone else that might be scratching their head - in my case, I had the `two_factor` app listed before my overriding app in `INSTALLED_APPS`, (oops!) so my particular issue is resolved
