### ISSUE TITLE
Migration for webauthn fails due to unique index on LONGTEXT not supported by MySQL/MariaDB

### ISSUE THREAD

**Issue by mastacheata** [jazzband/django-two-factor-auth#594]
## Expected Behavior

The Migration plugins/webauthn/migrations/0001_initial.py should run fine in MySQL

## Current Behavior

The migration plugins/webauthn/migrations/0001_initial.py fails with an error complaining you can't create an index on BLOB./TEXT columns without specifying a key length.

## Possible Solution

- Use a prefix-index => bad, because it only guarantees the prefix is unique, not the whole key
- Verify uniqueness in python-code => Bad, because it's a performance bottleneck
- Drop the uniqueness requirement => Probably the best idea, the public key attestation in WebAuthN devices should be unique anyways.

## Steps to Reproduce (for bugs)

1. Install django-two-factor-auth[webauthn]
2. Run ./manage.py migrate

## Context

This is a problem in MySQL/MariaDB for the most part because they don't support arbitrary length indexes on TEXT fields at all.
I've found reports of PostgreSQL exposing similar problems if the stored value is bigger than the pagesize of the Database Engine Index buffer, but couldn't verify that myself.

All in All it seems like a bad idea to Index a textfield that can store up to 1024 bytes (as of WebAuthN Level 5) or even infinite amounts of data (up until WebAuthN Level 4)

## Your Environment

* django-two-factor-auth version: 1.15
* Database: MariaDB 10.3

**Comment by mastacheata** [comment]
I'll add a tl;dr in hopes this helps get someone to look at this and decide how to tackle the problem:

MySQL doesn't support UNIQUE on TEXT fields as that potentially creates an infinitely large index.
Postgres works around that and dynamically extends the memory reservation for the index when needed (up to a certain maximum).

I don't think uniqueness is necessary at all.
If you wish to have it, Django should check before inserting without the database unneccessarily reserving memory for that.

**Comment by claudep** [comment]
@jpaniagualaconich What is your opinion here, do you think it should be relatively safe to drop the unique index on `public_key`?
An alternative would be to create a `UniqueConstraint` based on an expression (substring of public key), which would be ignored on MySQL < 8.0.13 and MariaDB as they don't support functional constraints.

**Comment by sevdog** [comment]
How about a `UniqueConstraint` using the hash of the public key?

Django ORM already has support for some DB [hash functions](https://docs.djangoproject.com/en/3.2/ref/models/database-functions/#sha1-sha224-sha256-sha384-and-sha512), for indexing purpose it could fit indexing the SHA1 of public key.

**Comment by claudep** [comment]
Sure, that's a good idea, but that doesn't change the fact that the unique index won't be enforced on MySQL < 8.0.13 and MariaDB for the reason given above.

**Comment by jpaniagualaconich** [comment]
Indeed it looks safe to drop. Shall we redo migration 0001 without it?

**Comment by claudep** [comment]
If it's safe to drop the index, then we should "simply" remove it and add a migration that applies that.

**Comment by jpaniagualaconich** [comment]
ok but 0001 will fail if you have MariaDB, if I understood correctly

**Comment by jpaniagualaconich** [comment]
We could except: pass that specific MariaDB error in 0001 and except: pass in 0002 when it tries to drop the unique index but it doesn't exist :thinking:

**Comment by sevdog** [comment]
> Sure, that's a good idea, but that doesn't change the fact that the unique index won't be enforced on MySQL < 8.0.13 and MariaDB for the reason given above.

An hash index should not give that kind of problem since it will index a fixed-length hash value rather than the whole text/blob. A double-check on MySQL/MariaDB doc is indeed required.

https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_sha1
https://mariadb.com/kb/en/sha1/

There is no statement regarding parameter length/size for the cryptographic hash functions.

It should be tested/experimented at least.

**Comment by sevdog** [comment]
This is a *knwon limitation* of Django ORM when dealing with these DBMS: https://docs.djangoproject.com/en/4.1/ref/databases/#textfield-limitations

**Comment by jpaniagualaconich** [comment]
ok, #610 should make everyone happy. I tried starting both with the constraint already in place and from scratch and "it works on my computer". More testing is always welcome.
