### ISSUE TITLE
Co-maintainer(s) needed!

### ISSUE THREAD

**Issue by claudep** [jazzband/django-two-factor-auth#595]
This package does need more Jazzbanders helping maintaining it, ideally people with some knowledge in authentication stuff (ideally more than me, which isn't very hard in fact :smile:).

Note the enforced commit policy is to require an approval for each commit, which is a good thing per se, but a bit hard to live when only one maintainer is really active (no offense to you @moggers87, your reviews are still MUCH appreciated).

**Comment by peymanslh** [comment]
@claudep 
I'm in jazzband for a while and contributing to some projects, and I'd be happy if there is anything that I can help with.

**Comment by claudep** [comment]
Thanks for the offer! As a first task, could you explore why the pre-commit is currently failing?

**Comment by stryker-sk** [comment]
I can also assist

**Comment by s-i-l-k-e** [comment]
@claudep our organisation uses this package and I'm a jazzbander, so I'm happy to assist as well. Let me know if there is anything I can do.

**Comment by claudep** [comment]
@peymanslh helped me a lot recently to review/approve patches. But being more that two active people would be awesome. So if you can take some time to review patches and triage tickets, that would be very much appreciated. Generally I find better to spend a little time regularly than 2 days per week and burning out quickly. You see what I mean... :smile: 

I'm closing the ticket now, but everyone is still welcome to help, of course.
