### ISSUE TITLE
Remove salted_hmac_sha256

### ISSUE THREAD

**Issue by sevdog** [jazzband/django-two-factor-auth#601]
Since now the minimun supported django version is 3.2
https://github.com/jazzband/django-two-factor-auth/blob/52b78a72fbfdeb356cadbc8faf23ac65a2141cc7/setup.py#L15

It does not make sense to keep this backported method and not use django `salted_hmac` instead.

https://github.com/jazzband/django-two-factor-auth/blob/52b78a72fbfdeb356cadbc8faf23ac65a2141cc7/two_factor/views/utils.py#L303-L310

**Comment by claudep** [comment]
Good catch, do you plan to suggest a pull request?

**Comment by sevdog** [comment]
@claudep I can provide a PR with this with ease.
