### ISSUE TITLE
Document(readthedocs.io) redirects to wrong version and raise 404

### ISSUE THREAD

**Issue by peymanslh** [jazzband/django-two-factor-auth#605]
When I hit `https://django-two-factor-auth.readthedocs.io` it redirects to `https://django-two-factor-auth.readthedocs.io/en/1.14.dev1/` and shows a 404 page, but when I enter `https://django-two-factor-auth.readthedocs.io/en/latest/` manually it works fine.

**Comment by swiss-knight** [comment]
PR #606 shall fix this issue.

**Comment by claudep** [comment]
I don't have access to this project's readthedocs config. @moggers87, @Bouke, do you know who have access and if I could be given access?
