### ISSUE TITLE
tokens -> token

### ISSUE THREAD

**Issue by DannyLee12** [jazzband/django-two-factor-auth#609]
https://github.com/jazzband/django-two-factor-auth/blob/6377d6cc4a9dd54cb557a053c9d9ca70fc54bfea/two_factor/locale/es/LC_MESSAGES/django.po#L188

**Comment by claudep** [comment]
The original string was fixed in the source code and in the pot file sent to Transifex. So if you translate through Transifex (https://explore.transifex.com/Bouke/django-two-factor-auth/), you should be fine and the .po will be fixed once we get the translations back.
