### ISSUE TITLE
Urgent: (TOTP)How to change the tolerance value for all users 

### ISSUE THREAD

**Issue by priyatamnayakwsp** [jazzband/django-two-factor-auth#617]
Hi ,
Want to make the TOTP tolerance value to 0, to make sure the current token is only valid.
Any setting is there to change the tolerance value for all users?
need urgent help.

@jezdez @matthiask @chipx86 @com4 @bmihelac

**Comment by claudep** [comment]
If you have an urgent issue, it may be time for you to hire a consultant, not summon a volunteer.
By the way, the ticket system is where you report bugs, not to ask for support questions, thanks for your understanding!
