### ISSUE TITLE
Django Admin error: Reverse for 'phone_create' not found. 'phone_create' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by mgax** [jazzband/django-two-factor-auth#627]
After dc6ad73, the Django Admin homepage fails with this error:

```
NoReverseMatch at /admin/
Reverse for 'phone_create' not found. 'phone_create' is not a valid view function or pattern name.
```

<img width="913" alt="Screenshot 2023-05-23 at 07 45 07" src="https://github.com/jazzband/django-two-factor-auth/assets/27617/132443cc-8569-4214-91ec-fd535feede37">

**Comment by dekkers** [comment]
I can not reproduce this, both with and without the phonenumber plugin the admin works for me. Do you have some custom admin code that might be causing this? Can you provide the full stack trace?

Note that phone_create is in the two_factor namespace, so getting the URL should be done with `reverse("two_factor:phone_create")`.

**Comment by mgax** [comment]
Apologies, it was a bug on my end. `reverse("two_factor:phone_create")` was being called even though `two_factor.plugins.phonenumber` is not enabled (because somebody thought "phone_create" was related to TOTP somehow).
