### ISSUE TITLE
Is it possible to have two active 2FAs, e.g., Yubikey and Authenticator App, so the user chooses what he/she wants to use?

### ISSUE THREAD

**Issue by statsconchris** [jazzband/django-two-factor-auth#628]
I couldn't find a similar issue listed. What class should I modify to achieve this?

Some websites give you the option to choose among all your login options, for example:
If I left my yubikey at home but I do have my phone with me, then I could choose to log in with my phone, and tomorrow I will do so with my yubikey...

Thanks for the answer

**Comment by claudep** [comment]
This was reported in #305.
