### ISSUE TITLE
Relaxing django-phonenumber-field version requirement?

### ISSUE THREAD

**Issue by apkallum** [jazzband/django-two-factor-auth#639]
Hello! I wanted to ask if there is a reason why django-phonenumber-field is pinned to below version 7? If there is no reason, could you update the version? I can open a little PR if needed.

**Comment by claudep** [comment]
Sure, please check the Changelog of django-phonenumber-field to see if any change might impact django-two-factor-auth and then suggest a PR.

**Comment by claudep** [comment]
@apkallum, gently ping about a PR for this issue

**Comment by mlec1** [comment]
@claudep I made an MR to update `django-phonenumber-field` to `v7`. I didn't notice any breaking changes affecting this library. The unit tests seem to pass successfully

**Comment by claudep** [comment]
Fixed by 2b4e8a5fe0b663812009ad3652863cee1d04604f
