### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by jzyworonek** [jazzband/django-two-factor-auth#653]
Hi. 

Can you please release the fix https://github.com/jazzband/django-two-factor-auth/pull/648. Currently `1.15.4` is unusable from a fresh install. I confirmed that latest master fixes the issue. Downgrading has even more issues with migrations so I would like to avoid that 🙃 

Thanks

**Comment by mlec1** [comment]
@claudep just a ping, in case you have time to do it

**Comment by claudep** [comment]
Sorry for this taking too long :disappointed:

@jpaniagualaconich, I was not able to find time for reviewing your remaining patches. What do you think about making a release now, and continue integrating your work later?

**Comment by jpaniagualaconich** [comment]
@claudep yes I think it will be a good thing for everyone. We can always follow up with point releases that include the rest.

**Comment by claudep** [comment]
Two PRs to review/approve: #668 and #669

**Comment by claudep** [comment]
1.15.5 was just released.

**Comment by mlec1** [comment]
Thank you for your time
