### ISSUE TITLE
Is it possible to use django-two-factor-auth with django-rest-knox? Is there a guide somewhere?

### ISSUE THREAD

**Issue by ocratravis** [jazzband/django-two-factor-auth#670]
I have a Django app which uses standard Django username/password login for authentication. I've integrated `django-two-factor-auth` into this login flow.

Now, I'm transitioning the app to a SPA (still built in Django).

So I'd like to use `django-rest-knox` for authentication. But I want to keep the 2FA functionality.

Is this possible? If so, is there some kind of documentation or tutorial?

**Comment by claudep** [comment]
I would suggest asking this on Django forums.
