### ISSUE TITLE
'two_factor' is not a registered tag library

### ISSUE THREAD

**Issue by carlosvega** [jazzband/django-two-factor-auth#677]
When I upgraded the code dependency I started to get the following error even though I have followed the CHANGELOG comments about adding to INSTALLED_APPS. Sorry for the bad report, unfortunately  I don't have more info to add.

```

    'two_factor',
    'two_factor.plugins.phonenumber',
```

## Expected Behavior
Run without issues like versions before.

## Current Behavior

`django.template.exceptions.TemplateSyntaxError: 'two_factor' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
filters
i18n
l10n
log
phonenumber
static
two_factor_tags
tz
`

## Possible Solution
For me, downgrade to version 1.13.2

## Steps to Reproduce (for bugs)
1. Install the version 1.15.1 or above

## Context
I was upgrading my code dependencies and suddenly the error happened. I have added the changes to INSTALLED_APPS

## Your Environment

* Browser and version:
* Python version:  3.9.18
* Django version: 3.2.22
* django-otp version: 1.2.4
* django-two-factor-auth version: 1.15.1

**Comment by claudep** [comment]
You should read release notes for 1.14.0, particularly the BREAKING line.

**Comment by carlosvega** [comment]
Hi. Thanks for the prompt answer.

I read it before opening the issue. Still, I didn't know what else should I change to make it work.

After some more testing I understood I was didn't change the way the templates are loaded with jinja...

I changed from `{% load i18n two_factor %}` to `{% load i18n two_factor_tags phonenumber %}`, and it now works. Thanks again.
