### ISSUE TITLE
Django-otp 1.3.0 broke tests

### ISSUE THREAD

**Issue by PetrDlouhy** [jazzband/django-two-factor-auth#684]
## Current Behavior

When tests are executed with `django-otp==1.3.0`, the following test fails:

```
======================================================================
FAIL: test_setup (tests.test_email.EmailTest.test_setup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/mock.py", line 1375, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petr/soubory/programovani/blenderkit/django-two-factor-auth/.tox/py311-dj42-yubikey/lib/python3.11/site-packages/django/test/utils.py", line 461, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/petr/soubory/programovani/blenderkit/django-two-factor-auth/tests/test_email.py", line 78, in test_setup
    self.assertEqual(len(mail.outbox), 1)
AssertionError: 0 != 1
```

## Expected Behavior
This doesn't happen if the version is `1.2.0`

## Steps to Reproduce (for bugs)

1. Update `django-otp` to 1.3.0
2. Run `tox -e py311-dj42-yubikey`

## Context
Tests in PRs #683 #682 #680 are affected by this.

**Comment by claudep** [comment]
Petr, may I ask you to approve the pull request linked above, if you are OK with it, of course?

**Comment by PetrDlouhy** [comment]
@claudep I have added approval review, but I am not sure if it helps. The change seems to be pretty simple.
I am not maintainer, so I can merge it.

**Comment by claudep** [comment]
Oh yes, I forgot that you have to be a Jazzband member (https://jazzband.co/) for the review to count. I'd hope that more Jazzbanders would follow this package to help with maintainership :persevere:
