### ISSUE TITLE
drf-spectacular does not show APIs

### ISSUE THREAD

**Issue by hosseinmp76** [jazzband/django-two-factor-auth#693]
[drf-spectacular](https://github.com/tfranzel/drf-spectacular) does not list django-two-factor-auth APIs. I can browse the URLs and views are working fine but they are not listed in drf-spectacular.
I could not find any document or issues related to this. Should I set any config?

**Comment by sergei-maertens** [comment]
this package doesn't ship API views as far as I can tell, so I'm not sure what exactly it is you expect?

**Comment by hosseinmp76** [comment]
Am I missing something or aren't these APIs? 

https://github.com/jazzband/django-two-factor-auth/blob/master/two_factor/urls.py

**Comment by sergei-maertens** [comment]
They are not, they're regular Django views.
