### ISSUE TITLE
Is there a migration guide for 1.15?

### ISSUE THREAD

**Issue by jcgiuffrida** [jazzband/django-two-factor-auth#697]
## Expected Behavior
I am upgrading my site's Django implementation and need to upgrade `django-two-factor-auth`. However, it looks like the `phonenumbers` portion, which I use, has been separated into a plugin. I'm trying to see how this will impact my site and the stored phone numbers. 

## Current Behavior
The initial migrations for this appear to **delete all existing phone devices** and force everyone to set up 2FA again. At least, I don't see any alternative to doing this. I am not sure what code I may need to change and what other impacts there could be. I don't know if trying to copy PhoneDevices to the new table manually will result in invalid authentication and lock everyone out.
The changelog does not explain what I need to do to upgrade safely. Various issues like https://github.com/jazzband/django-two-factor-auth/issues/611 make me very nervous about upgrading and potentially messing up my migration history or clearing the stored devices. I may be missing a migration guide somewhere. 

## Possible Solution
I need to know how to safely upgrade my version. Without any guidance my only alternative is to fork this project and fix the few issues with newer Django releases manually. 

Thanks

**Comment by jcgiuffrida** [comment]
(In case anyone is in my boat, it looks like you just have to replace `SuccessURLAllowedHostsMixin` in `views/core.py` with `RedirectURLMixin`. No guarantees though)

**Comment by claudep** [comment]
There is no migration guide apart what is written in release notes. And no, the `0008_delete_phonedevice.py` is not deleting anything at all, as it's a state only operation. If you put the phonenumber plugin explicitly in the installed apps, it should happily reuse the same table with the same data. Anyway, you should test a migration with a copy of the data before doing it in production.
