### ISSUE TITLE
Question: Is it possible to implement 2FA only for a specific site when you have multiple independent admin sites in django admin?

### ISSUE THREAD

**Issue by vshtishi** [jazzband/django-two-factor-auth#711]
I tried following the documentation to implement 2FA for only one of my multiple admin sites, but it is not working as expected. Is it possible to do and if so can you please provide some pointers as to how this can be achieved?

**Comment by moggers87** [comment]
No, we don't provide any support for Django's "sites" framework.

**Comment by vshtishi** [comment]
Thanks for answering 👍
