### ISSUE TITLE
Is it possible to extend the user model? 

### ISSUE THREAD

**Issue by Ezeko95** [jazzband/django-two-factor-auth#718]
Im trying to extend the user model to give them an authorization level. For example: "manager", "owner", "worker", etc. But im not finding anything in the documentation. 

## Expected Behavior
Be able to extend the user model attributes and add foreign keys so i can relate the User to other models.

## Current Behavior
No bug, just a question.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser and version:
* Python version:
* Django version:
* django-otp version:
* django-two-factor-auth version:
* Link to your project:

**Comment by moggers87** [comment]
The user model is part of Django's auth module. I believe this page should help you: https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#extending-the-existing-user-model

**Comment by Ezeko95** [comment]
I'll give it a try, thank you so much!
